// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Earth: typeof import('./components/content/Echerts/Earth.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElInput: typeof import('element-plus/es')['ElInput']
    Graph: typeof import('./components/content/Echerts/Graph.vue')['default']
    Icon: typeof import('./components/common/Icon/Icon.vue')['default']
    NewsControl: typeof import('./components/content/NewsControl/NewsControl.vue')['default']
    NewsList: typeof import('./components/content/NewsList/NewsList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
