// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CommonButton: typeof import('./components/common/CommonButton/CommonButton.vue')['default']
    Earth: typeof import('./components/content/Echerts/Earth.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Graph: typeof import('./components/content/Echerts/Graph.vue')['default']
    Icon: typeof import('./components/common/Icon/Icon.vue')['default']
    InputControl: typeof import('./components/common/InputControl/InputControl.vue')['default']
    NewsControl: typeof import('./components/content/NewsControl/NewsControl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
